/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import com.jtattoo.plaf.mcwin.McWinLookAndFeel;
import datos.Conexion;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author Admin
 */
public class FrmInicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form InicioSesion_S
     */
    public FrmInicioSesion() {
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Opciones = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        TfUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TfContraseña = new javax.swing.JPasswordField();
        BtnIngresar = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INICIO DE SESION");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("\"ALTAGRACIA\"");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 90, 580, 70));

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Seleccione una opción:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        Opciones.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        Opciones.setForeground(new java.awt.Color(51, 51, 51));
        Opciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vendedor", "Propietario", " " }));
        Opciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcionesActionPerformed(evt);
            }
        });
        jPanel1.add(Opciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 180, 30));

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Usuario:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        TfUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(TfUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 180, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contraseña:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));

        TfContraseña.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(TfContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 180, -1));

        BtnIngresar.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        BtnIngresar.setText("Ingresar");
        BtnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

        BtnSalir.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(BtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, 110, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("FARMACIA ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 20, 580, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 620));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formularios/iconos/Farmaceutica.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void BtnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIngresarActionPerformed

        Connection conn = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
       

        if (TfUsuario.getText().isEmpty() || TfContraseña.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor escriba su usuario y contraseña", "Iniciar sesión",
                    JOptionPane.INFORMATION_MESSAGE);

        }

        try {
    
            CallableStatement cst = Conexion.obtConexion().prepareCall("{CALL IniciarSesion (?,?)}");
            cst.setString(1, (TfUsuario.getText()));
            cst.setString(2, (TfContraseña.getText()));
            rs= cst.executeQuery();

            boolean entra = false;

            if (rs.next()) {
                JOptionPane.showMessageDialog(this, "Bienvenido");
                entra = true;
                if(TfUsuario.getText() !="admin"){
                   
                }
                FrmIntermedia inter = new FrmIntermedia();
                inter.setVisible(true);
                this.setVisible(false);
                //FrmIntermedia.EmpleadosRegistrosE.setEnabled(false);
                //FrmIntermedia.RegistroProveedor.setEnabled(false);

            } else {
                JOptionPane.showMessageDialog(null, "Por favor escriba su usuario y contraseña", "Iniciar sesión",
                        JOptionPane.INFORMATION_MESSAGE);
                TfUsuario.setText(" ");
                TfContraseña.setText(" ");
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);

        }


    }//GEN-LAST:event_BtnIngresarActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int opcion = JOptionPane.showConfirmDialog(null,
                "Está seguro que quiere cerrar la aplicación?",
                "Confirmación de cierre", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (opcion == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void OpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpcionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {

            //</editor-fold>
            UIManager.setLookAndFeel(new McWinLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(FrmInicioSesion.class.getName()).log(Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnIngresar;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JComboBox<String> Opciones;
    private javax.swing.JPasswordField TfContraseña;
    private javax.swing.JTextField TfUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
